### ISSUE TITLE
Value ranges?

### ISSUE THREAD

**Issue by chucker** [hsluv/hsluv-csharp#2]
The [Ruby](https://github.com/hsluv/hsluv-ruby) and [Swift](https://github.com/hsluv/hsluv-swift) implementations seem to suggest that hue is between 0 and 360, and saturation and lightness are between 0 and 100. However, passing `100` for saturation seems to result in a far less saturated color than passing, say, `255`.

Here's the code I use:

```csharp
var rgbRaw = Hsluv.HsluvConverter.HsluvToRgb(new[] { hue, 100, 75 });
var rgbClamped = rgbRaw.Select(x => Math.Clamp((int)(x * 256), 0, 255)).ToList();
fill.Colour = Color.FromArgb(rgbClamped[0], rgbClamped[1], rgbClamped[2]);
```

Hue and lightness look right, but saturation seems to be too low.

Is there an example of valid values?

**Comment by boronine** [comment]
Hi @chucker I might be able to help you if you can simplify your example. Can you provide a pair of specific HSLuv values that result in a discrepancy? Once you do that, can you replicate your issue using the colour picker? https://www.hsluv.org

**Comment by chucker** [comment]
Thanks for getting back to me, but I'm afraid I can't reproduce the issue.

For reference, it indeed looks like input values to `HsluvToRgb` range from `[0..<360]`, `[0..<100]`, `[0..<100]`, and output values are all `[0..<1]`.
